=== c-jordi/geonetwork/schema/geonet_alpha0.1.json
{
    "$id": "https://geonetwork.io/schemas/alpha0.1.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Geonetwork",
    "type": "object",
    "required": ["nodes"],
    "properties": {
        "title": {
            "type": "string",
            "description": "Title of the geonetwork file."
        },
        "author": {
            "type":"string",
            "description": "Name(s) of the author(s). Comma seperated."
        },
        "description": {
            "type": "string",
            "description": "Description of the data contained in the geonetwork."
        },
        "uid": {
            "type": "string"
        },
        "geonet": {
            "type": "string"
        },
        "created": {
            "$ref" : "#/$defs/datetime"
        },
        "edited": {
            "$ref" : "#/$defs/datetime"
        },
        "nodes": {
            "type": "array",
            "uniqueItems": true,
            "minItems": 1,
            "items": {
                "type": "object",
                "required" : ["id"],
                "properties": {
                    "id" : {
                        "type": "string"
                    },
                    "coordinates" : {
                        "$ref": "#/$defs/coordinates"
                    },
                    "label": {
                        "type": "string"
                    },
                    "class": {
                        "type": "string"
                    },
                    "from": {
                        "$ref" : "#/$defs/datetime"
                    },
                    "to": {
                        "$ref" : "#/$defs/datetime"
                    },
                    "properties": {
                        "$ref": "#/$defs/properties"
                    },
                    "states": {
                        "$ref": "#/$defs/states"
                    }
                }
            }
        },
        "edges":{
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "source" : {
                    "$def": "#/$defs/node_ref"
                    },
                    "target": {
                        "$def": "#/$defs/node_ref"
                    },
                    "id": {
                        "type": "string"
                    },
                    "label": {
                        "type": "string"
                    },
                    "class": {
                        "type": "string"
                    },
                    "from": {
                        "$ref" : "#/$defs/datetime"
                    },
                    "to": {
                        "$ref": "#/$defs/datetime"
                    },
                    "properties": {
                        "$ref": "#/$defs/properties"
                    },
                    "states": {
                        "$ref": "#/$defs/states"
                    },
                    "path": {
                        "type": "array"
                    }
                }
            }   
        },
        "settings": {
            "type": "object",
            "properties": {
                "cursor": {
                    "$ref": "#/$defs/datetime"
                },
                "viewbox": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/coordinate"
                    },
                    "minItems": 4
                },
                "legend": {
                    "type": "array"
                }
            }
        }
    },
    "$defs": {
        "datetime" : {
            "type": "string"
        },
        "coordinates": {
            "type": "array",
            "minItems": 2,
            "items": {
                "$ref" : "#/$defs/coordinate"
            }
        },
        "coordinate": {
            "type": "number",
            "description": "Coordinate provided in the WSG 1984 system."
        },
        "properties": {
            "type": "object",
            "properties": {
                "$size": {
                    "$ref" : "#/$defs/pixel"
                },
                "$fill": {
                    "$ref": "#/$defs/colorstring"
                },
                "$stroke": {
                    "$ref": "#/$defs/colorstring"
                }
            }
        },
        "states": {
            "type": "array",
            "items": {
                "$ref": "#/$refs/state"
            }
        },
        "state": {
            "type": "object",
            "anyOf" : [
                {"required": ["from"]},
                {"required": ["to"]}
            ],
            "properties": {
                "from": {
                    "$ref": "#/$defs/datetime"
                },
                "to": {
                    "$ref": "#/$defs/datetime"
                }
            }
        },
        "node_ref": {
            "OneOf" : [
                {"type": "integer", "minimum": 0},
                {"type": "string", "minLength": 1}
            ]
        },
        "pixel": {
            "type": "number",
            "minimum": 0
        },
        "colorstring": {
            "type": "string"
        }
    }
  }

=== c-jordi/geonetwork/examples/CO2_network.json
{
    "title": "CO2 Network",
    "geonet": "latest",
    "nodes": [
        {
            "id": "zurich",
            "label": "Zurich",
            "class": "emitter",
            "coordinates": [
                47.3775499,
                8.4666751
            ],
            "properties": {
                "owner": "Sunshine Inc.",
                "active_since": 2009,
                "emissions_tCO2" : 3e6,
                "$size": 20
            }
        },
        {
            "id": "basel",
            "label": "Basel",
            "class": "emitter",
            "coordinates": [
                47.5546492,
                7.5594405
            ]
        },
        {
            "id": "mont-terri",
            "label": "Mont Terri",
            "class": "storage",
            "coordinates": [
                47.389468,
                7.0985558
            ]
        },
        {
            "id": "thun",
            "label": "Thun",
            "class": "emitter",
            "coordinates": [
                46.7402635,
                7.6031855
            ]
        }
        
    ],
    "edges": [
        {
            "source": "zurich",
            "target": "basel",
            "class": "rail",
            "properties": {
                "built_in": 2009,
                "maintained_by": "SBB",
                "$size": 3
            },
            "states" : [
                {"to":"2022-12-31", "flow_tCO2":10, "$size": 3},
                {"from": "2022-12-31", "to":"2023-12-31", "flow_tCO2":20, "$size": 5},
                {"from": "2023-12-31", "to":"2024-12-31", "flow_tCO2 ":40, "$size": 9}
            ]
        },
        {
            "source": "thun",
            "target": "basel",
            "class": "truck",
            "properties": {
                "total_fleet": 400,
                "$size": 3
            }
        },
        {
            "source": "basel",
            "target": "mont-terri",
            "class": "pipeline",
            "properties": {
                "built_in": 2015,
                "$size": 7
            }
        } 
        
    ],
    "settings": {
        "cursor": "start",
        "legend": [
            {"type":"node", "class":"emitter", "label": "CO2 emitter", "$fill": "#fbb13c"},
            {"type":"node", "class":"storage", "label": "Storage site", "$fill": "#424242"},
            {"type":"edge", "class":"truck", "label": "Truck", "$stroke": "#535353"},
            {"type":"edge", "class":"pipeline", "label": "Pipeline", "$stroke": "#218380"},
            {"type":"edge", "class":"rail", "label": "Rail", "$stroke": "#a8322d"}
        ],
        "view": [
            47.3775499,
            8.4666751
        ],
        "zoom": 10
    }
}

=== c-jordi/geonetwork/examples/European_trade.json
{
    "title": "European Trade",
    "geonet": "latest",
    "nodes": [
        {
            "id": "France",
            "class": "EU",
            "coordinates": [
                48.8588336,
                2.2769954
            ],
            "properties": {
                "emissions": "126,634,806 tCO2",
                "$size": 20,
                "$fill": "blue"
            }
        },
        {
            "id": "Germany",
            "class": "EU",
            "coordinates": [
                52.5065133,
                13.144555
            ],
            "properties": {
                "emissions": "487,004,055 tCO2",
                "$size": 30,
                "$fill": "red"
            }
        }
    ],
    "edges": [
    ],
    "settings": {
        "cursor": "start",
        "legend": [],
        "view": [
            47.3775499,
            8.4666751
        ],
        "zoom": 4
    }
}
